project_id = "bywimfvrbcjcktqzdvmk"

[functions.weather-forecast]
verify_jwt = false

[functions.csc-location]
verify_jwt = false

[functions.paymongo-webhook]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false
